"""Signal wrappers for the Altium netlist pipeline."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING

from .altium_netlist_model import HierarchyPath
from .altium_netlist_signal_context import (
    AltiumSignalContext,
    AltiumSignalType,
)

if TYPE_CHECKING:
    from .altium_netlist_signal_context import (
        AltiumSignalPinInfo,
        AltiumSignalUniquePinsQueryContext,
    )
    from .altium_netlist_signal_objects import AltiumObjectInfo
    from .altium_netlist_visited import AltiumVisitedObjectsManager


class AltiumSignalRange(Enum):
    """Signal scope classification for the netlist pipeline."""

    GLOBAL = "global"
    LOCAL = "local"


@dataclass(slots=True)
class AltiumSignalFullNameInfo:
    """Resolved signal name and naming metadata."""

    base_name: str
    source_object_id: str | None = None
    channel_designator_format: str = ""
    sheet_number: str = ""
    diff_pair_suffix: str = ""
    bus_signal_suffix: str = ""
    pin_name: str = ""
    has_pin_source: bool = False
    has_autogenerated_full_name: bool = False
    full_name: str | None = None

    @property
    def name(self) -> str:
        """Return the base derived signal name from the stored fields."""

        if not self.has_pin_source:
            return self.base_name + self.diff_pair_suffix + self.bus_signal_suffix
        separator = "_" if self.pin_name else ""
        return f"Net{self.base_name}{separator}{self.pin_name}"

    def define_full_name(self, with_diff_pair_suffix: bool = True) -> str:
        """Rebuild the effective signal full name."""

        diff_suffix = self.diff_pair_suffix if with_diff_pair_suffix else ""
        if not self.bus_signal_suffix:
            multi_channel_name = _apply_channel_designator(
                self.base_name,
                self.channel_designator_format,
            )
            if self.has_pin_source:
                separator = "_" if self.pin_name else ""
                return f"Net{multi_channel_name}{separator}{self.pin_name}"
            return f"{multi_channel_name}{self.sheet_number}{diff_suffix}"
        return _apply_channel_designator(
            f"{self.base_name}{diff_suffix}{self.bus_signal_suffix}",
            self.channel_designator_format,
        )

    def __post_init__(self) -> None:
        if self.full_name is None:
            self.full_name = self.define_full_name()


class AltiumSignalInfo:
    """Base signal wrapper that delegates content to its context."""

    def __init__(
        self,
        signal_id: str,
        full_name_info: AltiumSignalFullNameInfo,
        context: AltiumSignalContext | None = None,
    ) -> None:
        self.id = signal_id
        self.full_name_info = full_name_info
        self.context = context or AltiumSignalContext()
        self.is_hidden = False
        self.context.set_signal(self)

    @property
    def objects(self) -> tuple[AltiumObjectInfo, ...]:
        """Return the context-owned trace objects."""

        return self.context.objects

    @property
    def content_count(self) -> int:
        """Return the combined object and pin count."""

        return self.context.content_count

    @property
    def content(self) -> tuple[AltiumObjectInfo | AltiumSignalPinInfo, ...]:
        """Return the ordered context content."""

        return self.context.content

    def get_range(self) -> AltiumSignalRange:
        raise NotImplementedError

    def get_signal_type(self) -> AltiumSignalType:
        """Delegate signal type lookup to the context."""

        return self.context.get_signal_type()

    def get_all_pins(self) -> tuple[AltiumSignalPinInfo, ...]:
        """Return all context pins."""

        return self.context.get_all_pins()

    def get_unique_pins(
        self,
        context: AltiumSignalUniquePinsQueryContext | None = None,
    ) -> tuple[AltiumSignalPinInfo, ...]:
        """Return de-duplicated pins from the context."""

        return self.context.get_unique_pins(context)

    def add_pin(self, new_pin: AltiumSignalPinInfo) -> None:
        """Attach and append a pin to the context."""

        self.context.add_pin(new_pin)

    def add_objects(
        self,
        new_objects: list[AltiumObjectInfo]
        | tuple[AltiumObjectInfo, ...]
        | AltiumVisitedObjectsManager,
    ) -> None:
        """Attach and append objects to the context."""

        self.context.add_objects(new_objects)

    def sort_pins(self) -> None:
        """Sort pins inside the context."""

        self.context.sort_pins()

    def sort_objects(self) -> None:
        """Sort objects inside the context."""

        self.context.sort_objects()


class AltiumLocalSignalInfo(AltiumSignalInfo):
    """Signal wrapper for one schematic/hierarchy instance."""

    def __init__(
        self,
        signal_id: str,
        full_name_info: AltiumSignalFullNameInfo,
        schematic_id: str,
        hierarchy_path: HierarchyPath,
        context: AltiumSignalContext | None = None,
    ) -> None:
        super().__init__(signal_id, full_name_info, context)
        self.schematic_id = schematic_id
        self.hierarchy_path = hierarchy_path

    def get_range(self) -> AltiumSignalRange:
        return AltiumSignalRange.LOCAL


class AltiumGlobalSignalInfo(AltiumSignalInfo):
    """Signal wrapper aggregated across one or more local signals."""

    def __init__(
        self,
        signal_id: str,
        full_name_info: AltiumSignalFullNameInfo,
        context: AltiumSignalContext | None = None,
        esd_interface_name: str = "",
        esd_signal_name: str = "",
    ) -> None:
        super().__init__(signal_id, full_name_info, context)
        self.local_signals: list[AltiumLocalSignalInfo] = []
        self.esd_interface_name = esd_interface_name
        self.esd_signal_name = esd_signal_name

    @property
    def pins(self) -> tuple[AltiumSignalPinInfo, ...]:
        """Return the global signal pins."""

        return self.get_all_pins()

    @property
    def schematic_ids(self) -> tuple[str, ...]:
        """Return distinct schematic IDs referenced by local signals."""

        return tuple(
            dict.fromkeys(
                local_signal.schematic_id for local_signal in self.local_signals
            ),
        )

    def get_range(self) -> AltiumSignalRange:
        return AltiumSignalRange.GLOBAL

    def add_local_signal(self, new_local_signal: AltiumLocalSignalInfo) -> None:
        """Append one local signal to the aggregation."""

        self.local_signals.append(new_local_signal)

    def add_local_signals(
        self,
        new_local_signals: list[AltiumLocalSignalInfo] | tuple[AltiumLocalSignalInfo, ...],
    ) -> None:
        """Append multiple local signals to the aggregation."""

        self.local_signals.extend(new_local_signals)


def _apply_channel_designator(name: str, channel_designator_format: str) -> str:
    if not channel_designator_format:
        return name
    if "{}" in channel_designator_format:
        return channel_designator_format.format(name)
    if "%s" in channel_designator_format:
        return channel_designator_format.replace("%s", name)
    return f"{name}{channel_designator_format}"


__all__ = [
    "AltiumGlobalSignalInfo",
    "AltiumLocalSignalInfo",
    "AltiumSignalFullNameInfo",
    "AltiumSignalInfo",
    "AltiumSignalRange",
]
