from __future__ import annotations

import argparse
import sys
import tomllib
from collections import defaultdict
from pathlib import Path


PUBLIC_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = PUBLIC_ROOT / "examples"
MANIFEST_PATH = EXAMPLES_ROOT / "manifest.toml"
EXAMPLES_INDEX_PATH = PUBLIC_ROOT / "docs" / "examples" / "index.md"


def _load_manifest() -> list[dict[str, object]]:
    manifest = tomllib.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    examples = manifest.get("examples", [])
    if not isinstance(examples, list):
        raise TypeError("examples/manifest.toml must contain an examples list")
    return examples


def _as_str_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str)]


def _escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _example_id(example: dict[str, object]) -> str:
    example_id = str(example.get("id", "")).strip()
    if not example_id:
        raise ValueError("examples/manifest.toml contains an example without id")
    return example_id


def _example_readme_link(example: dict[str, object]) -> str:
    doc = str(example.get("doc", "")).strip()
    if not doc:
        return ""
    return f"../../examples/{doc}"


def _example_label(example: dict[str, object]) -> str:
    example_id = _escape_table_cell(_example_id(example))
    title = _escape_table_cell(str(example.get("title", "")).strip())
    link = _example_readme_link(example)
    label = f"[`{example_id}`]({link})" if link else f"`{example_id}`"
    if title:
        return f"{label}<br>{title}"
    return label


def _format_example_row(example: dict[str, object]) -> str:
    areas = _escape_table_cell(", ".join(_as_str_list(example.get("areas"))) or "-")
    tags = _escape_table_cell(", ".join(_as_str_list(example.get("tags"))[:6]) or "-")
    summary = _escape_table_cell(str(example.get("summary", "")))
    return f"| {_example_label(example)} | {areas} | {summary} | {tags} |"


def render_examples_index(examples: list[dict[str, object]]) -> str:
    by_area: dict[str, list[dict[str, object]]] = defaultdict(list)
    for example in examples:
        areas = _as_str_list(example.get("areas")) or ["other"]
        by_area[areas[0]].append(example)

    lines = [
        "# Examples",
        "",
        "<!-- generated by tools/generate_docs.py; edit examples/manifest.toml or example README files instead -->",
        "",
        "Public examples are indexed from `examples/manifest.toml`.",
        "",
        f"Total examples: `{len(examples)}`",
        "",
        "## Generate",
        "",
        "From the repository root:",
        "",
        "```powershell",
        "uv run python tools\\generate_docs.py",
        "```",
        "",
        "## By Area",
        "",
    ]

    for area in sorted(by_area):
        area_examples = sorted(by_area[area], key=lambda item: str(item.get("id", "")))
        lines.extend(
            [
                f"### `{area}`",
                "",
                "| Example | Areas | Summary | Tags |",
                "| --- | --- | --- | --- |",
            ]
        )
        lines.extend(_format_example_row(example) for example in area_examples)
        lines.append("")

    lines.extend(
        [
            "## Complete List",
            "",
            "| Example | Areas | Summary | Tags |",
            "| --- | --- | --- | --- |",
        ]
    )
    lines.extend(_format_example_row(example) for example in examples)
    lines.append("")

    return "\n".join(lines)


def write_docs(*, check: bool) -> int:
    rendered = render_examples_index(_load_manifest())
    if check:
        existing = (
            EXAMPLES_INDEX_PATH.read_text(encoding="utf-8")
            if EXAMPLES_INDEX_PATH.exists()
            else ""
        )
        if existing != rendered:
            print(f"generated docs are stale: {EXAMPLES_INDEX_PATH}", file=sys.stderr)
            return 1
        return 0

    EXAMPLES_INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    EXAMPLES_INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {EXAMPLES_INDEX_PATH.relative_to(PUBLIC_ROOT)}")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate public documentation inputs."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated documentation files are not current.",
    )
    args = parser.parse_args(argv)
    return write_docs(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
